#!/bin/dash

boldon=$(tput bold)
boldoff=$(tput sgr0)

javac *.java

if [ "$#" -eq 1 ]; then
    filename="$1"
    java Scanner < "$filename" > mine.txt
    java -jar "./scantest/scanner.jar" < "$filename" > ref.txt
    diff --brief "mine.txt" "ref.txt" \
        && echo "cool!" || vimdiff "mine.txt" "ref.txt" 
else
    for filename in $(ls -1 "./test"); do
        echo "$boldon $filename $boldoff" 
        java Scanner < "./test/$filename" > mine.txt
        java -jar "./scantest/scanner.jar" < "./test/$filename" > ref.txt
        diff --brief "mine.txt" "ref.txt" && echo "cool!"
    done
fi
